language: python

TestingStage: &testingStage
  stage: test
  dist: xenial
  install:
    - pip install -r test_requirements.txt
  script:
    - python setup.py install
    - py.test --cov-report term --cov=pySmartDL -v
    - codecov

after_failure:
  - dmesg | tail -n 100 

jobs:
  include:
    - <<: *testingStage
      python: 3.4
    - <<: *testingStage
      python: 3.5
    - <<: *testingStage
      python: 3.6
    - <<: *testingStage
      python: 3.7
    - <<: *testingStage
      python: 3.8

    - stage: Deploy
      if: tag =~ /^v
      dist: trusty
      python: 3.6
      skip-cleanup: true
      install:
        - pip install -r build_requirements.txt
      script:
        - cd docs
        - make html
        - touch _build/html/.nojekyll  # for github pages
        - cd ..  # return to root folder
      deploy:
        - provider: pages
          local-dir: docs/_build/html
          target-branch: gh-pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          on:
            all_branches: true  # actually based on the tag
        - provider: pypi
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          skip_existing: true
          skip-cleanup: true
          distributions: "sdist bdist_wheel"
          on:
            all_branches: true  # actually based on the tag
